server:
  port: 8004
spring:
  application:
    name: starry-sky-userinfo
  datasource:
    url: jdbc:mysql://localhost:3306/starry_sky?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456

eureka:
  instance:
    hostname: userinfo-eureka
    instance-id: userinfo-8004
    prefer-ip-address: true
    #  Eureka 服务端在收到最后一次心跳后等待时间上限，单位秒默认90,秒，超时将剔除服务
    lease-expiration-duration-in-seconds: 2
    # Eureka  客户端向服务端发送心跳的时间间隔，单位秒 默认30秒
    lease-renewal-interval-in-seconds: 1
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      # 集群
      #      defaultZone: http://:7001/eureka,http://eureka7002.com:7002/eureka

      defaultZone: http://localhost:7001/eureka  # 单机版